Database: 
  host: ""
  port: ""
  user: ""
  database: ""
  password: ""
  
Request:
  host: ""
  basepath: ""
  path:  ""
  
smtp:
  user: ""
  password: ""
  from: ""
  to: ""
  host: ""
  port: ""
  
